### ISSUE TITLE
ruby doproxy.rb print error

### ISSUE THREAD

**Issue by ranjeetranjan** [thisismitch/doproxy#3]
Hi,

When I execute ruby doproxy.rb print getting below error.

root@doproxy:~/doproxy# ruby doproxy.rb print
/root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/uri/generic.rb:1100:in `rescue in merge': bad URI(is not URI?): /v2/droplets/12042416 (URI::InvalidURIError)
        from /root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/uri/generic.rb:1097:in`merge'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:406:in `build_exclusive_url'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:192:in`build_env'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in`run_request'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.4/lib/resource_kit/action_invoker.rb:34:in`response'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.4/lib/resource_kit/action_invoker.rb:18:in `handle_response'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.4/lib/resource_kit/action_invoker.rb:14:in`call'
        from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.4/lib/resource_kit/method_factory.rb:16:in `block in method_for_action'
        from doproxy.rb:39:in`block in get_inventory'
        from doproxy.rb:38:in `each_line'
        from doproxy.rb:38:in`get_inventory'
        from doproxy.rb:29:in `initialize'
        from doproxy.rb:140:in`new'
        from doproxy.rb:140:in `<main>'

**Comment by ftheo** [comment]
So I got this error too with Ruby 2.2.2. You can see the error [here](https://www.digitalocean.com/community/questions/ruby-doproxy-rb-create-error) too. They suggest to stick with Ruby 2.1.5 

I had to install ruby 2.2.2 instead of 2.1.5 that the README says because with 2.1.5 while trying to install droplet_kit I got the following error

`ERROR:  Error installing droplet_kit:
    activesupport requires Ruby version >= 2.2.2.`

To be able to use droplet_kit with ruby 2.1.5 I had to first install another version of activesupport that did support ruby 2.1.5 simply by installing it manually

`gem install activesupport`

Then I installed the droplet_kit as per the README

`gem install droplet_kit`

Now you should not see the errors. Hope this helps
