### ISSUE TITLE
invalid image error

### ISSUE THREAD

**Issue by stephenamsel** [thisismitch/doproxy#4]
Hello,

I have successfully tested DOProxy and generated a default Ubuntu server under my load balancer. However, when I try to switch images to one in my account, I receive the following error:
(DropletKit::FailedCreate)
    from /usr/share/rvm/gems/ruby-2.1.5/gems/droplet_kit-1.4.1/lib/droplet_kit/resources/droplet_resource.rb:18:in `block (3 levels) in <class:DropletResource>'
    from /usr/share/rvm/gems/ruby-2.1.5/gems/resource_kit-0.1.5/lib/resource_kit/action_invoker.rb:19:in`instance_exec'
    from /usr/share/rvm/gems/ruby-2.1.5/gems/resource_kit-0.1.5/lib/resource_kit/action_invoker.rb:19:in `handle_response'
    from /usr/share/rvm/gems/ruby-2.1.5/gems/resource_kit-0.1.5/lib/resource_kit/action_invoker.rb:14:in`call'
    from /usr/share/rvm/gems/ruby-2.1.5/gems/resource_kit-0.1.5/lib/resource_kit/method_factory.rb:16:in `block in method_for_action'
    from doproxy.rb:64:in`create_server'
    from doproxy.rb:146:in `<main>'

The only change I made was in the DOProxy YML file, switching the "image" line to "image: test-server". The size of the server being opened is the same as that of the droplet from which I took the snapshot, a DO standard 1gb server.  Do I need to add any further information because the image is a snapshot within my account rather than one of the DO defaults? What can I do to fix this?

**Comment by andrewsomething** [comment]
`image` should be the ID for the image. Only publicly available images have "slugs" like `ubuntu-14-04-x64`  You can find the ID of an image using:

``` bash
curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DO_TOKEN" "https://api.digitalocean.com/v2/images?private=true"
```

This will return only your images. The response will contain the ID and look like:

``` json
{ "images": [
  {
    "id": 5812587,
    "name": "foobar",
    "distribution": "Ubuntu",
    "slug": null,
    "public": false,
    "regions": [
      "nyc3"
    ],
    "created_at": "2014-08-27T04:00:47Z",
    "min_disk_size": 30,
    "type": "snapshot"
  }
]}
```

So if that is the snapshot you want to use, then you'd put `image: 5812587` in the yaml file.

**Comment by stephenamsel** [comment]
Thanks! It worked perfectly.
